config/routes.rb
Rails.application.routes.draw do
  resources :maps, only: [:show]
  get "calendar" => "calendar#index"
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "dashboards", to: "dashboards#index"
    resources :kinds
    resources :users, only: [:destroy]
    resources :events, only: [:new, :index, :show, :edit, :destroy, :create, :update]
    resources :entries, only: [:index, :destroy]
    resources :orders, only: [:index]
  end

  scope module: :public do
    devise_for :users
    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
    root to: "homes#top"
    get "/homes/about" => "homes#about", as: "about"
    get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe" # 退会確認画面
    patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal" # 論理削除
    get "/homes/goodbye" => "homes#goodbye", as: "goodbye"

    resources :pets, only: [:new, :create, :index, :show, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :pets, only: [:new, :index, :show, :edit, :destroy, :create, :update]
    resources :events, only: [:index, :show]
    get "/events/index", to: "events#index", defaults: { format: "json" }
    resources :entries, only: [:create, :index, :destroy, :update, :show] do
      member do
        patch "increase"
        patch "decrease"
      end
    end
    resources :orders, only: [:new, :create, :index, :show]
    patch "/orders/new" => "orders#new"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/thanks" => "orders#thanks"
    resources :addresses, only: [:index, :edit, :update]
  end
  resources :notifications, only: [:update]
  get "/search" => "searches#search"
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: "Favorite"
  belongs_to :kind

  validates :name, presence: true
  # validates :kind, presence: true
  validates :image, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg")
    else
      image
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == "perfect"
      Pet.where(name: content)
    elsif method == "forward"
      Pet.where("name LIKE ?", content + "%")
    elsif method == "backward"
      Pet.where("name LIKE ?", "%" + content)
    else
      Pet.where("name LIKE ?", "%" + content + "%")
    end
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def new
    @pet = Pet.new
  end
  
  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id
    @pet.save
    redirect_to pets_path(params[:id])
  end

  def index
    @pets = Pet.page(params[:page]).per(10)
    @pet = Pet.new
    @user = current_user
  end

  def show
    @pet = Pet.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @user = current_user
    @pet = Pet.find(params[:id])
    unless @pet.user == current_user
      redirect_to pets_path
    end
  end
  
  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      @user = current_user
      flash[:notice] = "You have updated pet successfully."
      redirect_to pet_path(@pet.id)
    else
      flash.now[:notice]
      render :edit
    end
  end

  def destroy
    pet = Pet.find(params[:id])
    pet.destroy
    redirect_to pets_path
  end
  
  private
  
  def pet_params
    params.require(:pet).permit(:name, :image, :kind, :caption)
  end
  
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/destroy.html.erb
<h1>Pets#destroy</h1>
<p>Find me in app/views/pets/destroy.html.erb</p>

app/views/pets/edit.html.erb
<h1>Post Edit</h1>

<% if @pet.errors.any? %>
  <%= @pet.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @pet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

        <%= form_with model: @pet do |f| %>
          <label for="inputName">Name</label>
          <br>
          <%= f.text_field :name, autofocus: true, id:"inputName"%>
          <br>
          <label for="inputKind">Kind</label>
          <%= f.text_field :kind, autofocus: true, id:"inputKind" %>
          <br>
          <label for="inputCaption">Caption</label>
          <%= f.text_field :caption, autofocus: true, id:"inputCaption" %>
          <br>
          <%= f.submit "Update Pet" %>
        <% end %>
        
        <%= link_to "Show", pet_path(@pet.id) %>
        |
        <%= link_to "Back", pets_path %>

app/views/pets/index.html.erb
<h1>Pets</h1>

  <% if user_signed_in? %>
 
        <div>
          <% @pets.each do |pet| %>
              <div class="row">
                <%= link_to pet_path(pet.id) do %>
                  <%= image_tag pet.get_image %>
                <% end %>
              </div>
              <div>
                <%= pet.name %>
                <%= pet.kind %>
                <%= pet.caption %>
              </div>
              <div class="row">
                <%= link_to user_path(pet.user.id) do%>
                  <%= image_tag pet.user.get_profile_image %>
                <% end %>
              </div>
              <div class="row">
                <%= link_to user_path(pet.user.id) do%>
                  <%= pet.user.name %>
                <% end %>
              </div>
          <% end %>
        </div>

　<% else %>
        <div>
          <% @pets.each do |pet| %>

              <div class="row">
                <%= link_to pet_path(pet.id) do %>
                  <%= image_tag pet.get_image %>
                <% end %>
              </div>
              <div>
                <%= pet.name %>
                <%= pet.kind %>
                <%= pet.caption %>
              </div>
              <div>
                <%= link_to "#{pet.comments.count} Comment", pet_path(pet.id) %>
              </div>
          <% end %>
        </div>
  
  <% end %>

<%= paginate @pets %>

app/views/pets/new.html.erb
<h1>Post</h1>

<%= form_with model: @pet do |f| %>
  <h4>image</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>pet's name</h4>
  <%= f.text_field :name %>

  <h4>kind</h4>
  <%= f.text_field :kind %>

  <h4>caption</h4>
  <%= f.text_area :caption %>

  <%= f.submit '投稿' %>
<% end %>

app/views/pets/show.html.erb
<h1>Pet</h1>

<div>
  <%= image_tag @pet.get_image %>
  <p>name：<%= @pet.name %></p>
  <p>kind：<%= @pet.kind %></p>
  <p>caption：<%= @pet.caption %></p>
  <p><%#= image_tag 'sample-author1.jpg' %></p>
  <p><%= @pet.user.name %></p>
  <p><%= @pet.created_at.strftime('%Y/%m/%d') %></p>
  
  <% if @pet.user == current_user %>
    <%= link_to "Edit", edit_pet_path(@pet.id) %>
    <%= link_to "Destroy", pet_path(@pet.id), method: :delete, "data-confirm" =>"Are you sure?" %>
  <% end %>
</div>

<div>
  <p>Comment counts：<%= @pet.comments.count %></p>
  <% @pet.comments.each do |comment| %>
    <p><%= image_tag comment.user.get_profile_image %></p>
    <%= comment.user.name %>
    <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
    <% if comment.user == current_user %>
      <%= link_to "Delete", pet_comment_path(comment.pet, comment), method: :delete %>
    <% end %>
  <% end %>
    
  <% if @pet.favorited_by?(current_user) %>
    <p>
      <%= link_to pet_favorite_path(@pet), method: :delete do %>
        ♥<%= @pet.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to pet_favorite_path(@pet), method: :post do %>
        ♡<%= @pet.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>

<div>
  <%= form_with model: [@pet, @comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "Comment here" %>
    <%= f.submit "Create" %>
  <% end %>
</div>