config/routes.rb
Rails.application.routes.draw do
  resources :maps, only: [:show]
  get "calendar" => "calendar#index"
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "dashboards", to: "dashboards#index"
    resources :kinds
    resources :users, only: [:destroy]
    resources :events, only: [:new, :index, :show, :edit, :destroy, :create, :update]
    resources :entries, only: [:index, :destroy]
    resources :orders, only: [:index]
  end

  scope module: :public do
    devise_for :users
    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
    root to: "homes#top"
    get "/homes/about" => "homes#about", as: "about"
    get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe" # 退会確認画面
    patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal" # 論理削除
    get "/homes/goodbye" => "homes#goodbye", as: "goodbye"

    resources :pets, only: [:new, :create, :index, :show, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :pets, only: [:new, :index, :show, :edit, :destroy, :create, :update]
    resources :events, only: [:index, :show]
    get "/events/index", to: "events#index", defaults: { format: "json" }
    resources :entries, only: [:create, :index, :destroy, :update, :show] do
      member do
        patch "increase"
        patch "decrease"
      end
    end
    resources :orders, only: [:new, :create, :index, :show]
    patch "/orders/new" => "orders#new"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/thanks" => "orders#thanks"
    resources :addresses, only: [:index, :edit, :update]
  end
  resources :notifications, only: [:update]
  get "/search" => "searches#search"
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :pets
end

app/controllers/admin/kinds_controller.rb
class Admin::KindsController < ApplicationController
  layout "admin"

  def new
    @kind = Kind.new
    @kinds = Kind.all
  end

  def create
    @kind = Kind.new(kind_params)
    if @kind.save
      flash[:notice] = "You have registered the new kind successfully!"
      redirect_to new_admin_kind_path
    else
      flash[:notice] = "Failed to register the new kind...."
      render :new
    end
  end

  def index
    @kinds = Kind.all
    # @kind = Kind.find(params[:id])
  end

  def edit
    @kind = Kind.find(params[:id])
  end

  def update
    @kind = Kind.find(params[:id])
    if @kind.update(kind_params)
      flash[:notice] = "You have updated kind successfully!"
      render :index
    else
      flash.now[:notice]
      render :edit
    end
  end

  def destroy
    @kinds = Kind.find(params[:id])
    @kinds.destroy
    flash[:notice] = "Deleted kind!!"
    redirect_to new_admin_kind_path
  end

  private
    def kind_params
      params.require(:kind).permit(:kind)
    end
end

app/helpers/admin/kinds_helper.rb
module Admin::KindsHelper
end

app/views/admin/kinds/_index.html.erb
<div class="container mb-7">
  <div class="row mt-4 md-px-20 sm-px-10 p-4">
    <h3>Kind List</h3>
    <table class="table">
      <tbody>
        <% kinds.each do |kind| %>
          <tr>
            <td>No. <%= kind.id %></td>
            <td><%= kind.kind %></td>
            <td><%= link_to 'Edit', edit_admin_kind_path(kind.id), class: 'btn btn-outline-primary' %></td>
            <td><%= link_to 'Destroy', admin_kind_path(kind.id), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/kinds/edit.html.erb
<%= render "admin/layouts/header" %>
<div class="container">
  <h1>Kind Edit</h1>
  
  <% if @event.errors.any? %>
    <%= @event.errors.count %>error prohibited this obj from being saved:
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
  <div class="row">
    <%= form with url: admin_kind_path(@kind.id), modek: @kind, method: :patch do |f| %>
    <label for="inputKind">Kind</label>Kind
    <br>
    <%= f.text_field :kind, autofocus: true, id:"inputKind" %>
    <%= f.submit "Update Kind", class: "btn btn-warning my-3" %>
    <br>
    <%= link_to "Back", new_admin_kind_path %>
  </div>
</div>

app/views/admin/kinds/index.html.erb
<%= render "admin/layouts/header" %>

<div class="container">
  <div class="row">
    <div class="col-12 my-3">
      
      <h3>Kind List</h3>
      <table class="table">
        <tbody>
          <% @kinds.each do |kind| %>
            <tr>
              <td>No. <%= kind.id %></td>
              <td><%= kind.kind %></td>
              <td><%= link_to 'Edit', edit_admin_kind_path(kind.id), class: 'btn btn-outline-primary' %></td>
              <td><%= link_to 'Delete', admin_kind_path(kind.id), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/kinds/new.html.erb
<%= render "admin/layouts/header" %>

      
      <!--ジャンル登録-->
<div class="container py-5">
  <div class="row mt-4 md-px-20 sm-px-10 p-4">

    <h2>Registration of Kind</h2>
    <div class="col col-10">
      <%= form_with model: @kind, url: admin_kinds_path do |f| %>
        <div class="body">
          <div class="col">
            <div class="field">
              <p class="registration-kind">
                <i class="fas fa-tablet-android"></i>Kind
              </p>
              <%= f.text_field :kind %>
            </div>
          </div>
          <div class="action">
            <%= f.submit 'Create Kind', class: "btn btn-warning mt-2" %>
         </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= render 'admin/kinds/index', kinds: @kinds %>