config/routes.rb
Rails.application.routes.draw do
  resources :maps, only: [:show]
  get "calendar" => "calendar#index"
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "dashboards", to: "dashboards#index"
    resources :kinds
    resources :users, only: [:destroy]
    resources :events, only: [:new, :index, :show, :edit, :destroy, :create, :update]
    resources :entries, only: [:index, :destroy]
    resources :orders, only: [:index]
  end

  scope module: :public do
    devise_for :users
    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
    root to: "homes#top"
    get "/homes/about" => "homes#about", as: "about"
    get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe" # 退会確認画面
    patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal" # 論理削除
    get "/homes/goodbye" => "homes#goodbye", as: "goodbye"

    resources :pets, only: [:new, :create, :index, :show, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :pets, only: [:new, :index, :show, :edit, :destroy, :create, :update]
    resources :events, only: [:index, :show]
    get "/events/index", to: "events#index", defaults: { format: "json" }
    resources :entries, only: [:create, :index, :destroy, :update, :show] do
      member do
        patch "increase"
        patch "decrease"
      end
    end
    resources :orders, only: [:new, :create, :index, :show]
    patch "/orders/new" => "orders#new"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/thanks" => "orders#thanks"
    resources :addresses, only: [:index, :edit, :update]
  end
  resources :notifications, only: [:update]
  get "/search" => "searches#search"
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @user = current_user
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]

    # 選択したモデルに応じて検索を実行
    if @model == "user"
      @records = User.search_for(@content, @method)
    elsif @model == "pet"
      @records = Pet.search_for(@content, @method)
      if params[:kind_id].present?
        @records = @records.where(kind_id: params[:kind_id]).page(params[:page])
      end
    elsif @model == "event"
      @records = Event.search_for(@content, @method)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<div class="col-md-12 col-sm-10 mx-2 mx-sm-auto">
  <% if user_signed_in? %>
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field :content %>
          <%= f.select :model, options_for_select({"User" => "user", "Event" => "event", "Pet" => "pet"}) %>
          <%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
          <%= f.collection_select(:kind_id, Kind.all, :id, :kind, prompt: "種類を選択してください") %>
          
          <%= f.submit "検索" %>
        <% end %>
  <% end %>
</div>

app/views/searches/_genre.html.erb
<div class="col-md-12 col-sm-10 mx-2 mx-sm-auto">
  <% if user_signed_in? %>
  <!--ジャンル絞り込み-->
    <%= form_with method: :get, url: pets_path do |f| %>
      <%= f.collection_select(:kind_id, Kind.all, :id, :kind, prompt: "種類を選択してください") %>
      <%= f.submit "絞り込む" %>
    <% end %>
  <% end %>
</div>

app/views/searches/search.html.erb
<!--<div class="container">-->
  <% if user_signed_in? %>
<!--    <#%= render 'layouts/list', user: @user, pets: @pets %>-->
<!--    <#%= render "searches/form" %>-->
    
    <div class="col-10">
    <% if @model == 'user' %>
      <h3>Users search for "<%= @content %>"</h3>
      <%= render 'public/users/index', users: @records %>
    <% elsif @model == 'pet' %>
      <h3>Pets search for "<%= @content %>"</h3>
      <%= render 'public/pets/index', pets: @records %>
    <% elsif @model == 'event' %>
      <h3>Events search for "<%= @content %>"</h3>
      <%= render 'public/events/index', events: @records %>
    <% end %>
    </div>
  <% end %>
<!--</div>-->

app/views/searches/search_result.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% elsif %>
    <tbody>
      <% @pets.each do |pet| %>
        <tr>
          <td><%= pet.name %></td>
          <td><%= pet.kind %></td>
        </tr>
      <% end %>
    </tbody>
  <% elsif %>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>