config/routes.rb
Rails.application.routes.draw do
  resources :maps, only: [:show]
  get "calendar" => "calendar#index"
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "dashboards", to: "dashboards#index"
    resources :kinds
    resources :users, only: [:destroy]
    resources :events, only: [:new, :index, :show, :edit, :destroy, :create, :update]
    resources :entries, only: [:index, :destroy]
    resources :orders, only: [:index]
  end

  scope module: :public do
    devise_for :users
    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end
    root to: "homes#top"
    get "/homes/about" => "homes#about", as: "about"
    get "/users/:id/unsubscribe" => "users#unsubscribe", as: "unsubscribe" # 退会確認画面
    patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal" # 論理削除
    get "/homes/goodbye" => "homes#goodbye", as: "goodbye"

    resources :pets, only: [:new, :create, :index, :show, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :pets, only: [:new, :index, :show, :edit, :destroy, :create, :update]
    resources :events, only: [:index, :show]
    get "/events/index", to: "events#index", defaults: { format: "json" }
    resources :entries, only: [:create, :index, :destroy, :update, :show] do
      member do
        patch "increase"
        patch "decrease"
      end
    end
    resources :orders, only: [:new, :create, :index, :show]
    patch "/orders/new" => "orders#new"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/thanks" => "orders#thanks"
    resources :addresses, only: [:index, :edit, :update]
  end
  resources :notifications, only: [:update]
  get "/search" => "searches#search"
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!
  def index
    @users = User.all
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<%= render "admin/layouts/header" %>
<div class="container">
  <h1>Hello Admin!</h1>
  <div class="row m-5">
    
    <div class="col">
      <%= link_to 'Create Event', new_admin_event_path, class: "btn btn-warning btn-block", data: {turbolinks: "false"} %>
    </div>
  </div>
  <h3>All Users</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>name</th>
        <th>E-mail</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th>
            <%= user.name %>
          </th>
          <th>
            <%= user.email %>
          </th>
          <th>
            <% if user.is_deleted == false %>
              <%= link_to 'Destroy', admin_user_path(user), method: :delete, class: 'btn btn-outline-danger', data: { confirm: 'Are you sure？' } %>
            <% else %>
            退会済
            <% end %>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>